imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: @JimsPeteBundle/Resources/config/admin.yml }



# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    app_locales: cn|en
    locale: zh_CN

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies:  [127.0.0.1]
    session:
        # handler_id set to null will use default session handler from php.ini
        #handler_id:  snc_redis.session.client
        #handler_id:  ~
        cookie_lifetime: 3600
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'SonataCoreBundle:Form:datepicker.html.twig'
    form_themes:
            - 'JimsUiopBundle:Form:form_ueditor_type.html.twig'
            - 'JimsUiopBundle:Form:form_type_test.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ JimsPeteBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        # enable metadata caching
        #metadata_cache_driver: redis
        # enable query caching
        #query_cache_driver: redis
        second_level_cache:
            enabled: false
        #    log_enabled: true
        #    region_cache_driver: ?

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


#snc_redis:
#    # configure predis as client
#    clients:
#        default:
#            type: predis
#            alias: default
#            options:
#                prefix : "sf_def:"
#            dsn: redis://192.168.58.90
#            logging: %kernel.debug%
#        session:
#            type: predis
#            alias: session
#            dsn: redis://192.168.58.90
#        cache:
#            type: predis
#            alias: cache
#            dsn: redis://secret@localhost/1
#            options:
#                profile: 2.2
#                connection_timeout: 10
#                read_write_timeout: 30
#        doctrine:
#            type: predis
#            alias: doctrine
#            options:
#                prefix : "sf_doc:"
#            dsn: redis://192.168.58.90
#    # configure doctrine caching
#    doctrine:
#        metadata_cache:
#            client: doctrine
#            entity_manager: default
#            document_manager: default
#        result_cache:
#            client: doctrine
#            #entity_manager: [default]
#            entity_manager: [default, read]
#        query_cache:
#            client: doctrine
#            entity_manager: default
#    session:
#        client: session
#        prefix: "sf_session"
#        use_as_default: true
#        ttl: 1200

sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]

sonata_admin:
    title:  测试用后台
    #title_logo: ~

    dashboard:
        groups:
            admin_group:
                label: 管理组列表
            admin_post:
                label: 文章列表

    templates:
        user_block: JimsPeteBundle:Admin:user_block.html.twig